name: CI Service Discovery

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: cakes-management-system/ci-cd/.github/workflows/build-with-maven.yml@master
    with:
      display-name: Service Discovery
      sonar: true
      sonar-project-key: cakes-management-system_service-discovery
      publish: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
